// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Playlist {
  final String id;
  final String name;
  final String? description;
  final String createdAt;

  const Playlist({
    required this.id,
    required this.name,
    this.description,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ description.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Playlist &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          createdAt == other.createdAt;
}
