// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AudioVersion {
  final String id;
  final String songId;
  final String filepath;
  final String originalName;
  final String? format;
  final int? bitrate;
  final int? sampleRate;
  final double duration;
  final PlatformInt64 fileSize;
  final bool isEnabled;
  final bool isPrimary;
  final String? md5;
  final int? bitDepth;

  const AudioVersion({
    required this.id,
    required this.songId,
    required this.filepath,
    required this.originalName,
    this.format,
    this.bitrate,
    this.sampleRate,
    required this.duration,
    required this.fileSize,
    required this.isEnabled,
    required this.isPrimary,
    this.md5,
    this.bitDepth,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      songId.hashCode ^
      filepath.hashCode ^
      originalName.hashCode ^
      format.hashCode ^
      bitrate.hashCode ^
      sampleRate.hashCode ^
      duration.hashCode ^
      fileSize.hashCode ^
      isEnabled.hashCode ^
      isPrimary.hashCode ^
      md5.hashCode ^
      bitDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioVersion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          songId == other.songId &&
          filepath == other.filepath &&
          originalName == other.originalName &&
          format == other.format &&
          bitrate == other.bitrate &&
          sampleRate == other.sampleRate &&
          duration == other.duration &&
          fileSize == other.fileSize &&
          isEnabled == other.isEnabled &&
          isPrimary == other.isPrimary &&
          md5 == other.md5 &&
          bitDepth == other.bitDepth;
}

class PreviewInfo {
  final String filepath;
  final String filename;
  final String title;
  final String artist;

  const PreviewInfo({
    required this.filepath,
    required this.filename,
    required this.title,
    required this.artist,
  });

  @override
  int get hashCode =>
      filepath.hashCode ^ filename.hashCode ^ title.hashCode ^ artist.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewInfo &&
          runtimeType == other.runtimeType &&
          filepath == other.filepath &&
          filename == other.filename &&
          title == other.title &&
          artist == other.artist;
}

class Song {
  final String id;
  final String title;
  final String? artist;
  final String? album;
  final String? lyrics;
  final String? coverPath;
  final int rating;
  final String createdAt;
  final List<AudioVersion> versions;
  final List<Tag> tags;

  const Song({
    required this.id,
    required this.title,
    this.artist,
    this.album,
    this.lyrics,
    this.coverPath,
    required this.rating,
    required this.createdAt,
    required this.versions,
    required this.tags,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      lyrics.hashCode ^
      coverPath.hashCode ^
      rating.hashCode ^
      createdAt.hashCode ^
      versions.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Song &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          lyrics == other.lyrics &&
          coverPath == other.coverPath &&
          rating == other.rating &&
          createdAt == other.createdAt &&
          versions == other.versions &&
          tags == other.tags;
}

class Tag {
  final PlatformInt64 id;
  final String name;
  final String? color;
  final String? category;

  const Tag({required this.id, required this.name, this.color, this.category});

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ color.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          color == other.color &&
          category == other.category;
}
