// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/music.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/playlist.dart';
import 'models/song.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1881993710;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_aetheria',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiMusicAddSongsToPlaylist({
    required String playlistId,
    required List<String> songIds,
  });

  Future<Tag> crateApiMusicAddTag({
    required String name,
    String? color,
    String? category,
  });

  Future<Playlist> crateApiMusicCreatePlaylist({required String name});

  Future<void> crateApiMusicDeleteAudioVersion({required String versionId});

  Future<void> crateApiMusicDeletePlaylist({required String id});

  Future<void> crateApiMusicDeleteSong({required String songId});

  Future<void> crateApiMusicDeleteTag({required PlatformInt64 tagId});

  Future<String> crateApiMusicExportAudioFile({
    required String versionId,
    required String destPath,
  });

  Future<String> crateApiMusicGetLibraryPath();

  Future<List<String>> crateApiMusicGetPlaylistSongs({
    required String playlistId,
  });

  Future<List<Playlist>> crateApiMusicGetPlaylists();

  Future<List<Song>> crateApiMusicGetSongs();

  Future<List<Tag>> crateApiMusicGetTags();

  String crateApiSimpleGreet({required String name});

  Future<AudioVersion> crateApiMusicImportAudioVersionForSong({
    required String songId,
    required String filepath,
  });

  Future<Song> crateApiMusicImportSong({required String filepath});

  Future<void> crateApiMusicImportSongWithMetadata({
    required String filepath,
    required String title,
    required String artist,
  });

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiMusicInitializeLibraryPath({required String path});

  bool crateApiMusicIsLibraryInitialized();

  Future<List<PreviewInfo>> crateApiMusicPreviewAudioMetadata({
    required List<String> filepaths,
  });

  Future<void> crateApiMusicRemoveSongsFromPlaylist({
    required String playlistId,
    required List<String> songIds,
  });

  Future<void> crateApiMusicRenamePlaylist({
    required String id,
    required String name,
  });

  Future<void> crateApiMusicResetLibrary();

  Future<List<String>> crateApiMusicScanDirectoryForPreview({
    required String dirPath,
  });

  Future<int> crateApiMusicStartAudioServer();

  Future<void> crateApiMusicTagSong({
    required String songId,
    required PlatformInt64 tagId,
    required bool bind,
  });

  Future<void> crateApiMusicUpdateSongMetadata({
    required String songId,
    required String title,
    required String artist,
  });

  Future<void> crateApiMusicUpdateVersionDuration({
    required String versionId,
    required double duration,
  });

  Future<void> crateApiMusicUpdateVersionStatus({
    required String versionId,
    required bool isEnabled,
    required bool isPrimary,
  });

  Future<bool> crateApiMusicVerifyAudioFile({required String filepath});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiMusicAddSongsToPlaylist({
    required String playlistId,
    required List<String> songIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(playlistId, serializer);
          sse_encode_list_String(songIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicAddSongsToPlaylistConstMeta,
        argValues: [playlistId, songIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicAddSongsToPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "add_songs_to_playlist",
        argNames: ["playlistId", "songIds"],
      );

  @override
  Future<Tag> crateApiMusicAddTag({
    required String name,
    String? color,
    String? category,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(color, serializer);
          sse_encode_opt_String(category, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tag,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicAddTagConstMeta,
        argValues: [name, color, category],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicAddTagConstMeta => const TaskConstMeta(
    debugName: "add_tag",
    argNames: ["name", "color", "category"],
  );

  @override
  Future<Playlist> crateApiMusicCreatePlaylist({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playlist,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicCreatePlaylistConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicCreatePlaylistConstMeta =>
      const TaskConstMeta(debugName: "create_playlist", argNames: ["name"]);

  @override
  Future<void> crateApiMusicDeleteAudioVersion({required String versionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(versionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicDeleteAudioVersionConstMeta,
        argValues: [versionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicDeleteAudioVersionConstMeta =>
      const TaskConstMeta(
        debugName: "delete_audio_version",
        argNames: ["versionId"],
      );

  @override
  Future<void> crateApiMusicDeletePlaylist({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicDeletePlaylistConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicDeletePlaylistConstMeta =>
      const TaskConstMeta(debugName: "delete_playlist", argNames: ["id"]);

  @override
  Future<void> crateApiMusicDeleteSong({required String songId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(songId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicDeleteSongConstMeta,
        argValues: [songId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicDeleteSongConstMeta =>
      const TaskConstMeta(debugName: "delete_song", argNames: ["songId"]);

  @override
  Future<void> crateApiMusicDeleteTag({required PlatformInt64 tagId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(tagId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicDeleteTagConstMeta,
        argValues: [tagId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicDeleteTagConstMeta =>
      const TaskConstMeta(debugName: "delete_tag", argNames: ["tagId"]);

  @override
  Future<String> crateApiMusicExportAudioFile({
    required String versionId,
    required String destPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(versionId, serializer);
          sse_encode_String(destPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicExportAudioFileConstMeta,
        argValues: [versionId, destPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicExportAudioFileConstMeta =>
      const TaskConstMeta(
        debugName: "export_audio_file",
        argNames: ["versionId", "destPath"],
      );

  @override
  Future<String> crateApiMusicGetLibraryPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicGetLibraryPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicGetLibraryPathConstMeta =>
      const TaskConstMeta(debugName: "get_library_path", argNames: []);

  @override
  Future<List<String>> crateApiMusicGetPlaylistSongs({
    required String playlistId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(playlistId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicGetPlaylistSongsConstMeta,
        argValues: [playlistId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicGetPlaylistSongsConstMeta =>
      const TaskConstMeta(
        debugName: "get_playlist_songs",
        argNames: ["playlistId"],
      );

  @override
  Future<List<Playlist>> crateApiMusicGetPlaylists() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_playlist,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicGetPlaylistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicGetPlaylistsConstMeta =>
      const TaskConstMeta(debugName: "get_playlists", argNames: []);

  @override
  Future<List<Song>> crateApiMusicGetSongs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_song,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicGetSongsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicGetSongsConstMeta =>
      const TaskConstMeta(debugName: "get_songs", argNames: []);

  @override
  Future<List<Tag>> crateApiMusicGetTags() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tag,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicGetTagsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicGetTagsConstMeta =>
      const TaskConstMeta(debugName: "get_tags", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<AudioVersion> crateApiMusicImportAudioVersionForSong({
    required String songId,
    required String filepath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(songId, serializer);
          sse_encode_String(filepath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_audio_version,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicImportAudioVersionForSongConstMeta,
        argValues: [songId, filepath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicImportAudioVersionForSongConstMeta =>
      const TaskConstMeta(
        debugName: "import_audio_version_for_song",
        argNames: ["songId", "filepath"],
      );

  @override
  Future<Song> crateApiMusicImportSong({required String filepath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filepath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_song,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicImportSongConstMeta,
        argValues: [filepath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicImportSongConstMeta =>
      const TaskConstMeta(debugName: "import_song", argNames: ["filepath"]);

  @override
  Future<void> crateApiMusicImportSongWithMetadata({
    required String filepath,
    required String title,
    required String artist,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filepath, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(artist, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicImportSongWithMetadataConstMeta,
        argValues: [filepath, title, artist],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicImportSongWithMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "import_song_with_metadata",
        argNames: ["filepath", "title", "artist"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiMusicInitializeLibraryPath({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicInitializeLibraryPathConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicInitializeLibraryPathConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_library_path",
        argNames: ["path"],
      );

  @override
  bool crateApiMusicIsLibraryInitialized() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMusicIsLibraryInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicIsLibraryInitializedConstMeta =>
      const TaskConstMeta(debugName: "is_library_initialized", argNames: []);

  @override
  Future<List<PreviewInfo>> crateApiMusicPreviewAudioMetadata({
    required List<String> filepaths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(filepaths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_preview_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicPreviewAudioMetadataConstMeta,
        argValues: [filepaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicPreviewAudioMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "preview_audio_metadata",
        argNames: ["filepaths"],
      );

  @override
  Future<void> crateApiMusicRemoveSongsFromPlaylist({
    required String playlistId,
    required List<String> songIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(playlistId, serializer);
          sse_encode_list_String(songIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicRemoveSongsFromPlaylistConstMeta,
        argValues: [playlistId, songIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicRemoveSongsFromPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "remove_songs_from_playlist",
        argNames: ["playlistId", "songIds"],
      );

  @override
  Future<void> crateApiMusicRenamePlaylist({
    required String id,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicRenamePlaylistConstMeta,
        argValues: [id, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicRenamePlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "rename_playlist",
        argNames: ["id", "name"],
      );

  @override
  Future<void> crateApiMusicResetLibrary() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicResetLibraryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicResetLibraryConstMeta =>
      const TaskConstMeta(debugName: "reset_library", argNames: []);

  @override
  Future<List<String>> crateApiMusicScanDirectoryForPreview({
    required String dirPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dirPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicScanDirectoryForPreviewConstMeta,
        argValues: [dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicScanDirectoryForPreviewConstMeta =>
      const TaskConstMeta(
        debugName: "scan_directory_for_preview",
        argNames: ["dirPath"],
      );

  @override
  Future<int> crateApiMusicStartAudioServer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMusicStartAudioServerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicStartAudioServerConstMeta =>
      const TaskConstMeta(debugName: "start_audio_server", argNames: []);

  @override
  Future<void> crateApiMusicTagSong({
    required String songId,
    required PlatformInt64 tagId,
    required bool bind,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(songId, serializer);
          sse_encode_i_64(tagId, serializer);
          sse_encode_bool(bind, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicTagSongConstMeta,
        argValues: [songId, tagId, bind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicTagSongConstMeta => const TaskConstMeta(
    debugName: "tag_song",
    argNames: ["songId", "tagId", "bind"],
  );

  @override
  Future<void> crateApiMusicUpdateSongMetadata({
    required String songId,
    required String title,
    required String artist,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(songId, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(artist, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicUpdateSongMetadataConstMeta,
        argValues: [songId, title, artist],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicUpdateSongMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "update_song_metadata",
        argNames: ["songId", "title", "artist"],
      );

  @override
  Future<void> crateApiMusicUpdateVersionDuration({
    required String versionId,
    required double duration,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(versionId, serializer);
          sse_encode_f_64(duration, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicUpdateVersionDurationConstMeta,
        argValues: [versionId, duration],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicUpdateVersionDurationConstMeta =>
      const TaskConstMeta(
        debugName: "update_version_duration",
        argNames: ["versionId", "duration"],
      );

  @override
  Future<void> crateApiMusicUpdateVersionStatus({
    required String versionId,
    required bool isEnabled,
    required bool isPrimary,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(versionId, serializer);
          sse_encode_bool(isEnabled, serializer);
          sse_encode_bool(isPrimary, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMusicUpdateVersionStatusConstMeta,
        argValues: [versionId, isEnabled, isPrimary],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicUpdateVersionStatusConstMeta =>
      const TaskConstMeta(
        debugName: "update_version_status",
        argNames: ["versionId", "isEnabled", "isPrimary"],
      );

  @override
  Future<bool> crateApiMusicVerifyAudioFile({required String filepath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filepath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMusicVerifyAudioFileConstMeta,
        argValues: [filepath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicVerifyAudioFileConstMeta =>
      const TaskConstMeta(
        debugName: "verify_audio_file",
        argNames: ["filepath"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioVersion dco_decode_audio_version(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return AudioVersion(
      id: dco_decode_String(arr[0]),
      songId: dco_decode_String(arr[1]),
      filepath: dco_decode_String(arr[2]),
      originalName: dco_decode_String(arr[3]),
      format: dco_decode_opt_String(arr[4]),
      bitrate: dco_decode_opt_box_autoadd_i_32(arr[5]),
      sampleRate: dco_decode_opt_box_autoadd_i_32(arr[6]),
      duration: dco_decode_f_64(arr[7]),
      fileSize: dco_decode_i_64(arr[8]),
      isEnabled: dco_decode_bool(arr[9]),
      isPrimary: dco_decode_bool(arr[10]),
      md5: dco_decode_opt_String(arr[11]),
      bitDepth: dco_decode_opt_box_autoadd_i_32(arr[12]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AudioVersion> dco_decode_list_audio_version(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_version).toList();
  }

  @protected
  List<Playlist> dco_decode_list_playlist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playlist).toList();
  }

  @protected
  List<PreviewInfo> dco_decode_list_preview_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_preview_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Song> dco_decode_list_song(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_song).toList();
  }

  @protected
  List<Tag> dco_decode_list_tag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tag).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  Playlist dco_decode_playlist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Playlist(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      createdAt: dco_decode_String(arr[3]),
    );
  }

  @protected
  PreviewInfo dco_decode_preview_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PreviewInfo(
      filepath: dco_decode_String(arr[0]),
      filename: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      artist: dco_decode_String(arr[3]),
    );
  }

  @protected
  Song dco_decode_song(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Song(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_opt_String(arr[2]),
      album: dco_decode_opt_String(arr[3]),
      lyrics: dco_decode_opt_String(arr[4]),
      coverPath: dco_decode_opt_String(arr[5]),
      rating: dco_decode_i_32(arr[6]),
      createdAt: dco_decode_String(arr[7]),
      versions: dco_decode_list_audio_version(arr[8]),
      tags: dco_decode_list_tag(arr[9]),
    );
  }

  @protected
  Tag dco_decode_tag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Tag(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      color: dco_decode_opt_String(arr[2]),
      category: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioVersion sse_decode_audio_version(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_songId = sse_decode_String(deserializer);
    var var_filepath = sse_decode_String(deserializer);
    var var_originalName = sse_decode_String(deserializer);
    var var_format = sse_decode_opt_String(deserializer);
    var var_bitrate = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_sampleRate = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_duration = sse_decode_f_64(deserializer);
    var var_fileSize = sse_decode_i_64(deserializer);
    var var_isEnabled = sse_decode_bool(deserializer);
    var var_isPrimary = sse_decode_bool(deserializer);
    var var_md5 = sse_decode_opt_String(deserializer);
    var var_bitDepth = sse_decode_opt_box_autoadd_i_32(deserializer);
    return AudioVersion(
      id: var_id,
      songId: var_songId,
      filepath: var_filepath,
      originalName: var_originalName,
      format: var_format,
      bitrate: var_bitrate,
      sampleRate: var_sampleRate,
      duration: var_duration,
      fileSize: var_fileSize,
      isEnabled: var_isEnabled,
      isPrimary: var_isPrimary,
      md5: var_md5,
      bitDepth: var_bitDepth,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AudioVersion> sse_decode_list_audio_version(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioVersion>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_version(deserializer));
    }
    return ans_;
  }

  @protected
  List<Playlist> sse_decode_list_playlist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Playlist>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist(deserializer));
    }
    return ans_;
  }

  @protected
  List<PreviewInfo> sse_decode_list_preview_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PreviewInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_preview_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Song> sse_decode_list_song(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Song>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_song(deserializer));
    }
    return ans_;
  }

  @protected
  List<Tag> sse_decode_list_tag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Tag>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tag(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Playlist sse_decode_playlist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return Playlist(
      id: var_id,
      name: var_name,
      description: var_description,
      createdAt: var_createdAt,
    );
  }

  @protected
  PreviewInfo sse_decode_preview_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filepath = sse_decode_String(deserializer);
    var var_filename = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    return PreviewInfo(
      filepath: var_filepath,
      filename: var_filename,
      title: var_title,
      artist: var_artist,
    );
  }

  @protected
  Song sse_decode_song(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_lyrics = sse_decode_opt_String(deserializer);
    var var_coverPath = sse_decode_opt_String(deserializer);
    var var_rating = sse_decode_i_32(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_versions = sse_decode_list_audio_version(deserializer);
    var var_tags = sse_decode_list_tag(deserializer);
    return Song(
      id: var_id,
      title: var_title,
      artist: var_artist,
      album: var_album,
      lyrics: var_lyrics,
      coverPath: var_coverPath,
      rating: var_rating,
      createdAt: var_createdAt,
      versions: var_versions,
      tags: var_tags,
    );
  }

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_color = sse_decode_opt_String(deserializer);
    var var_category = sse_decode_opt_String(deserializer);
    return Tag(
      id: var_id,
      name: var_name,
      color: var_color,
      category: var_category,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_version(AudioVersion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.songId, serializer);
    sse_encode_String(self.filepath, serializer);
    sse_encode_String(self.originalName, serializer);
    sse_encode_opt_String(self.format, serializer);
    sse_encode_opt_box_autoadd_i_32(self.bitrate, serializer);
    sse_encode_opt_box_autoadd_i_32(self.sampleRate, serializer);
    sse_encode_f_64(self.duration, serializer);
    sse_encode_i_64(self.fileSize, serializer);
    sse_encode_bool(self.isEnabled, serializer);
    sse_encode_bool(self.isPrimary, serializer);
    sse_encode_opt_String(self.md5, serializer);
    sse_encode_opt_box_autoadd_i_32(self.bitDepth, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_audio_version(
    List<AudioVersion> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_version(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist(List<Playlist> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist(item, serializer);
    }
  }

  @protected
  void sse_encode_list_preview_info(
    List<PreviewInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_preview_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_song(List<Song> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_song(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tag(List<Tag> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tag(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_playlist(Playlist self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_preview_info(PreviewInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filepath, serializer);
    sse_encode_String(self.filename, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
  }

  @protected
  void sse_encode_song(Song self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_String(self.lyrics, serializer);
    sse_encode_opt_String(self.coverPath, serializer);
    sse_encode_i_32(self.rating, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_list_audio_version(self.versions, serializer);
    sse_encode_list_tag(self.tags, serializer);
  }

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.color, serializer);
    sse_encode_opt_String(self.category, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
