# Set the directory for this build only. Never modify the shared Flutter SDK.
if(DEFINED ENV{AETHERIA_LINUX_ENGINE_DIR} AND NOT "$ENV{AETHERIA_LINUX_ENGINE_DIR}" STREQUAL "")
  file(TO_CMAKE_PATH "$ENV{AETHERIA_LINUX_ENGINE_DIR}" AETHERIA_LINUX_ENGINE_DIR)
  string(TOLOWER "${CMAKE_BUILD_TYPE}" AETHERIA_RUNTIME_MODE)
  set(AETHERIA_ENGINE_BUNDLE "${AETHERIA_LINUX_ENGINE_DIR}/${AETHERIA_RUNTIME_MODE}")
  foreach(name libflutter_linux_gtk.so engine.version)
    if(NOT EXISTS "${AETHERIA_ENGINE_BUNDLE}/${name}")
      message(FATAL_ERROR "Missing custom ${AETHERIA_RUNTIME_MODE} engine: ${AETHERIA_ENGINE_BUNDLE}/${name}")
    endif()
  endforeach()
  file(READ "${AETHERIA_ENGINE_BUNDLE}/engine.version" AETHERIA_ENGINE_VERSION)
  function(aetheria_read_sdk_revision result)
    include("${FLUTTER_MANAGED_DIR}/ephemeral/generated_config.cmake")
    file(READ "${FLUTTER_ROOT}/bin/internal/engine.version" revision)
    set(${result} "${revision}" PARENT_SCOPE)
  endfunction()
  aetheria_read_sdk_revision(AETHERIA_SDK_ENGINE_VERSION)
  string(STRIP "${AETHERIA_ENGINE_VERSION}" AETHERIA_ENGINE_VERSION)
  string(STRIP "${AETHERIA_SDK_ENGINE_VERSION}" AETHERIA_SDK_ENGINE_VERSION)
  if(NOT AETHERIA_ENGINE_VERSION STREQUAL AETHERIA_SDK_ENGINE_VERSION)
    message(FATAL_ERROR "Custom engine revision does not match the Flutter SDK")
  endif()
  get_target_property(AETHERIA_FLUTTER_LINKS flutter INTERFACE_LINK_LIBRARIES)
  list(REMOVE_ITEM AETHERIA_FLUTTER_LINKS "${FLUTTER_LIBRARY}")
  set(FLUTTER_LIBRARY "${AETHERIA_ENGINE_BUNDLE}/libflutter_linux_gtk.so")
  set_property(TARGET flutter PROPERTY INTERFACE_LINK_LIBRARIES
    "${FLUTTER_LIBRARY};${AETHERIA_FLUTTER_LINKS}")
  message(STATUS "Using Aetheria Wayland EGL embedder: ${AETHERIA_ENGINE_BUNDLE}")
endif()
