// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AudioOutputInfo {
  final String deviceName;
  final int sampleRate;
  final int channels;
  final String sampleFormat;
  final String bufferSize;
  final String outputLatencyMode;
  final int outputBufferMs;
  final int queuedMs;
  final BigInt underruns;
  final BigInt clippedSamples;
  final double peakDb;

  const AudioOutputInfo({
    required this.deviceName,
    required this.sampleRate,
    required this.channels,
    required this.sampleFormat,
    required this.bufferSize,
    required this.outputLatencyMode,
    required this.outputBufferMs,
    required this.queuedMs,
    required this.underruns,
    required this.clippedSamples,
    required this.peakDb,
  });

  @override
  int get hashCode =>
      deviceName.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      sampleFormat.hashCode ^
      bufferSize.hashCode ^
      outputLatencyMode.hashCode ^
      outputBufferMs.hashCode ^
      queuedMs.hashCode ^
      underruns.hashCode ^
      clippedSamples.hashCode ^
      peakDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioOutputInfo &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          sampleFormat == other.sampleFormat &&
          bufferSize == other.bufferSize &&
          outputLatencyMode == other.outputLatencyMode &&
          outputBufferMs == other.outputBufferMs &&
          queuedMs == other.queuedMs &&
          underruns == other.underruns &&
          clippedSamples == other.clippedSamples &&
          peakDb == other.peakDb;
}
