// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/playlist.dart';
import '../models/song.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `estimate_duration_from_bitrate`, `estimate_duration_with_symphonia`, `reliable_duration`, `scan_directory`

bool isLibraryInitialized() =>
    RustLib.instance.api.crateApiMusicIsLibraryInitialized();

Future<void> initializeLibraryPath({required String path}) =>
    RustLib.instance.api.crateApiMusicInitializeLibraryPath(path: path);

Future<List<Song>> getSongs() => RustLib.instance.api.crateApiMusicGetSongs();

Future<List<Tag>> getTags() => RustLib.instance.api.crateApiMusicGetTags();

Future<List<Playlist>> getPlaylists() =>
    RustLib.instance.api.crateApiMusicGetPlaylists();

Future<int> startAudioServer() =>
    RustLib.instance.api.crateApiMusicStartAudioServer();

Future<String> getLibraryPath() =>
    RustLib.instance.api.crateApiMusicGetLibraryPath();

Future<Song> importSong({required String filepath}) =>
    RustLib.instance.api.crateApiMusicImportSong(filepath: filepath);

Future<void> importSongWithMetadata({
  required String filepath,
  required String title,
  required String artist,
}) => RustLib.instance.api.crateApiMusicImportSongWithMetadata(
  filepath: filepath,
  title: title,
  artist: artist,
);

Future<AudioVersion> importAudioVersionForSong({
  required String songId,
  required String filepath,
}) => RustLib.instance.api.crateApiMusicImportAudioVersionForSong(
  songId: songId,
  filepath: filepath,
);

Future<void> updateVersionStatus({
  required String versionId,
  required bool isEnabled,
  required bool isPrimary,
}) => RustLib.instance.api.crateApiMusicUpdateVersionStatus(
  versionId: versionId,
  isEnabled: isEnabled,
  isPrimary: isPrimary,
);

Future<void> updateSongMetadata({
  required String songId,
  required String title,
  required String artist,
}) => RustLib.instance.api.crateApiMusicUpdateSongMetadata(
  songId: songId,
  title: title,
  artist: artist,
);

Future<void> deleteSong({required String songId}) =>
    RustLib.instance.api.crateApiMusicDeleteSong(songId: songId);

Future<void> deleteAudioVersion({required String versionId}) =>
    RustLib.instance.api.crateApiMusicDeleteAudioVersion(versionId: versionId);

Future<bool> verifyAudioFile({required String filepath}) =>
    RustLib.instance.api.crateApiMusicVerifyAudioFile(filepath: filepath);

Future<Tag> addTag({required String name, String? color, String? category}) =>
    RustLib.instance.api.crateApiMusicAddTag(
      name: name,
      color: color,
      category: category,
    );

Future<void> updateTag({
  required PlatformInt64 tagId,
  required String name,
  String? color,
  String? category,
}) => RustLib.instance.api.crateApiMusicUpdateTag(
  tagId: tagId,
  name: name,
  color: color,
  category: category,
);

Future<void> deleteTag({required PlatformInt64 tagId}) =>
    RustLib.instance.api.crateApiMusicDeleteTag(tagId: tagId);

Future<void> tagSong({
  required String songId,
  required PlatformInt64 tagId,
  required bool bind,
}) => RustLib.instance.api.crateApiMusicTagSong(
  songId: songId,
  tagId: tagId,
  bind: bind,
);

Future<Playlist> createPlaylist({required String name}) =>
    RustLib.instance.api.crateApiMusicCreatePlaylist(name: name);

Future<void> deletePlaylist({required String id}) =>
    RustLib.instance.api.crateApiMusicDeletePlaylist(id: id);

Future<void> renamePlaylist({required String id, required String name}) =>
    RustLib.instance.api.crateApiMusicRenamePlaylist(id: id, name: name);

Future<void> addSongsToPlaylist({
  required String playlistId,
  required List<String> songIds,
}) => RustLib.instance.api.crateApiMusicAddSongsToPlaylist(
  playlistId: playlistId,
  songIds: songIds,
);

Future<void> removeSongsFromPlaylist({
  required String playlistId,
  required List<String> songIds,
}) => RustLib.instance.api.crateApiMusicRemoveSongsFromPlaylist(
  playlistId: playlistId,
  songIds: songIds,
);

Future<List<String>> getPlaylistSongs({required String playlistId}) =>
    RustLib.instance.api.crateApiMusicGetPlaylistSongs(playlistId: playlistId);

Future<List<String>> scanDirectoryForPreview({required String dirPath}) =>
    RustLib.instance.api.crateApiMusicScanDirectoryForPreview(dirPath: dirPath);

Future<List<PreviewInfo>> previewAudioMetadata({
  required List<String> filepaths,
}) => RustLib.instance.api.crateApiMusicPreviewAudioMetadata(
  filepaths: filepaths,
);

Future<void> resetLibrary() => RustLib.instance.api.crateApiMusicResetLibrary();

Future<String> exportAudioFile({
  required String versionId,
  required String destPath,
}) => RustLib.instance.api.crateApiMusicExportAudioFile(
  versionId: versionId,
  destPath: destPath,
);

Future<void> updateVersionDuration({
  required String versionId,
  required double duration,
}) => RustLib.instance.api.crateApiMusicUpdateVersionDuration(
  versionId: versionId,
  duration: duration,
);

Future<void> startRustPlayback({
  required String path,
  required double volume,
  required double pitch,
  required String algo,
  required double normalizationGain,
}) => RustLib.instance.api.crateApiMusicStartRustPlayback(
  path: path,
  volume: volume,
  pitch: pitch,
  algo: algo,
  normalizationGain: normalizationGain,
);

Future<void> pauseRustPlayback() =>
    RustLib.instance.api.crateApiMusicPauseRustPlayback();

Future<void> resumeRustPlayback() =>
    RustLib.instance.api.crateApiMusicResumeRustPlayback();

Future<void> seekRustPlayback({required double secs}) =>
    RustLib.instance.api.crateApiMusicSeekRustPlayback(secs: secs);

Future<void> stopRustPlayback() =>
    RustLib.instance.api.crateApiMusicStopRustPlayback();

Future<void> setRustVolume({required double vol}) =>
    RustLib.instance.api.crateApiMusicSetRustVolume(vol: vol);

Future<void> setRustPitch({required double pitch, required String algo}) =>
    RustLib.instance.api.crateApiMusicSetRustPitch(pitch: pitch, algo: algo);

Future<double> getRustPlaybackPosition() =>
    RustLib.instance.api.crateApiMusicGetRustPlaybackPosition();

Future<void> refreshSongDatabase() =>
    RustLib.instance.api.crateApiMusicRefreshSongDatabase();
